### PR TITLE
This is a sample OSLC client application that explores authentication, discovery & delegatedUI

### PR DESCRIPTION
**Pull request by jadelkhoury**
This is a sample OSLC client application that explores client authentication alternatives of (1) oauth (2) basic authentication
(3) no authentication.

The application also demonstrates how to discover OSLC services.

Finally, it demonstrates how to integrate Delegated-UI iframes into your
own web-based application.

This branch is meant to work with the pull request of Lyo.client https://github.com/eclipse/lyo.client/pull/77

### CODE REVIEW

**Comment by jadelkhoury** [comment]
I'd be nice to post a rough demo to explain it. Easier than writing more docs.
More importantly, I'd like a review of the changes to the client library https://github.com/eclipse/lyo.client/pull/77

**Comment by jadelkhoury** [comment]
@berezovskyi I see that a check failed (License Compliance — 9 issues found). I can't see the details since I seem to need an account on some site. What can we do about this?

**Comment by berezovskyi** [comment]
I just disabled FOSSA. There is no strict license policy here but I wanted to keep the GPL code away. They seem to have removed an option to do an overall scan of the project and show the badge and force a check on every PR.

**Comment by berezovskyi** [comment]
Please ignore it.

**Pull request merged**
