### PR TITLE
Switch to Lyo 6

### PR DESCRIPTION
**Pull request by berezovskyi**
PR not really ready for review but marking it such to start CI checks.

### CODE REVIEW

**Comment by berezovskyi** [comment]
https://github.com/OSLC/lyo-samples/actions/runs/8498767441

**Comment by berezovskyi** [comment]
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project lyo-client-samples: Compilation failure: Compilation failure: 
Error:  /home/runner/work/lyo-samples/lyo-samples/main/lyo-client-samples/src/main/java/org/eclipse/lyo/samples/client/automation/AutomationAdapter.java:[575,57] cannot access jakarta.ws.rs.core.Response
Error:    class file for jakarta.ws.rs.core.Response not found
```

@jadelkhoury could you please take a look?

**Comment by Jad-el-khoury** [comment]
Interesting. Why is this code already calling jakarta classes?
I can have a look.

**Comment by Jad-el-khoury** [comment]
But @berezovskyi I don't have the bandwidth a the moment to migrate these projects to 6.0.0.SNAPSHOT.
I think we can set them on 6.0.0.Alpha1 to make sure they can still run.
Focus (for now) should be to test with the refImpl. If we make job too big, we won't finish it.

**Comment by berezovskyi** [comment]
@Jad-el-khoury I understand. I was only thinking about upgrading https://github.com/OSLC/lyo-samples/tree/master/lyo-client-samples as we test this client code against multiple Jazz installs.

**Comment by Jad-el-khoury** [comment]
> @Jad-el-khoury I understand. I was only thinking about upgrading https://github.com/OSLC/lyo-samples/tree/master/lyo-client-samples as we test this client code against multiple Jazz installs.

I see! I can look into it. Remember that the refImpl has a client that tests all 4 servers (but I only migrated rm & the client). So, we are testing the client (but not lyo-samples).

**Comment by Jad-el-khoury** [comment]
@berezovskyi ! It builds fine locally. I can't even see a trace of "jakarta" in either pom.xml or java files - throughout the whole repo.
Could it be a problem in the Workflow configuration?

**Comment by berezovskyi** [comment]
Are you on the `b-lyo6` branch?

**Comment by Jad-el-khoury** [comment]
> Are you on the `b-lyo6` branch?

Believe so. this b-lyo6 's only change was to switch to 6.0.0.SNAPSHOT!

**Comment by Jad-el-khoury** [comment]
I am running the code under this repo.
I could see from error above that you are running this
`/home/runner/work/lyo-samples/lyo-samples/main/lyo-client-samples/src/main/java/org/eclipse/lyo/samples/client/automation/AutomationAdapter.java`

**Comment by berezovskyi** [comment]
> I can't even see a trace of "jakarta" in either pom.xml or java files - throughout the whole repo.

I think the error is that the client sample code is using lyo-client 6.0.0-SNAPSHOT that depends on jakarta stuff with the provided scope but the sample POM is still supplying Jersey 2.35 deps, thus jakarta classes cannot be found.

**Comment by berezovskyi** [comment]
I finally understand what was causing the differences. The CI results are correct, our local are not (I also got this branch to work locally). The reason is that our local mvn builds pull 6.0.0-SNAPSHOT from maven repos, but the CI config in question builds the latest Lyo commit from a given branch (I was using branch `b153-migrate-jaxrs-api-to-jakarta` in my CI launch instructions).

In other words, these are the errors you will see on this project/PR **after** the jakarta branch is merged into Lyo master.

**Pull request merged**
